import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { Toaster } from 'react-hot-toast'
const StoreProvider = dynamic(() => import('@/app/storeProvider'), {ssr: false})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Cricket Store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StoreProvider>
					<Toaster position="top-center" />
					<Header />
					{children}
				</StoreProvider>
			</body>
		</html>
	)
}
