import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { Toaster } from 'react-hot-toast'
import { Provider as ReduxProvider } from 'react-redux'
import { store } from '@/reduxStore/stores/store'
import StoreProvider from './storeProvider'
const CartProvider = dynamic(() => import('@/contexts/CartContext'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Cricket Store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StoreProvider>
					<CartProvider>
						<Toaster position="top-center" />
						<Header />
						{children}
					</CartProvider>
				</StoreProvider>
			</body>
		</html>
	)
}
